### ISSUE TITLE
Handling WebIDL types that doesn't map to a JS "interface"

### ISSUE THREAD

**Issue by teoli2003** [dontcallmedom/mdn-scaffold#10]
Hi!

In a lot of cases, the WebIDL definition of methods and properties leads to the creation of a return value of the form:
```
{{DOMxRef("InterfaceName")}}
```

These are JS objects.

There are a few WebIDL types that don't map to a JS object with the same name or not a JS object but to a JS primitive.

For example (not an exhaustive list):

Boolean maps to `A boolean value.`
CSSOMString, DOMString, … maps to `A string.`

There are likely a few more (but not that many, max 10, but I haven't counted!). New such mappings are rarely added to the WebIDL spec. Hardcoding it into the scaffold is likely the right way to go.

**Comment by dontcallmedom** [comment]
there is [code that is supposed to deal with this](https://github.com/dontcallmedom/mdn-scaffold/blob/6c314a898d650d3c89de44cf964a4763ae90226b/generate.js#L108) - I'm guessing this means it's not doing what it should in practice :)

Do you have an example I could use to debug this?

**Comment by teoli2003** [comment]
The page landed overnight so it doesn't appear anymore in mdn-gaps. Nevertheless, the type was `CSSOMString`, and it looks like it isn't listed there: https://github.com/dontcallmedom/mdn-scaffold/blob/6c314a898d650d3c89de44cf964a4763ae90226b/generate.js#L99

It was for this page: https://developer.mozilla.org/en-US/docs/Web/API/CSSImportRule/layerName

So I guess it is a trivial fix! (PR incoming)
